name: test

on: [ push ]

jobs:
 lint:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Set up Python 3.9
    uses: actions/setup-python@v2
    with:
     python-version: 3.9
  - run: pip install flake8
  - run: pip install mypy
  - run: flake8 run.py roop
  - run: mypy run.py roop
  - name: Checkout
    uses: actions/checkout@v2
  - name: Set up ffmpeg
    uses: FedericoCarboni/setup-ffmpeg@v2
  - name: Set up Python 3.9
    uses: actions/setup-python@v2
    with:
     python-version: 3.9
  - run: pip install -r requirements-headless.txt
  - run: python run.py -s .github/examples/12.png -t .github/examples/test.png -o .github/examples/output.png --frame-processor face_enhancer
